import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    screens: {
      xs: '480px',
      ss: '649px',
      sm: '768px',
      '2sm': '790px',
      md: '899px',
      lg: '1159px',
      '2lg': '1340px',
      xl: '1420px',
      // xl: '899 1100 1160 1340 1420 1920',
      '2xl': '1921px',
      narrow: { raw: '(max-aspect-ratio: 3 / 2)' },
      wide: { raw: '(min-aspect-ratio: 3 / 2)' },
      'taller-than-854': { raw: '(min-height: 854px)' },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        // accent: {
        //   DEFAULT: "hsl(var(--accent))",
        //   foreground: "hsl(var(--accent-foreground))",
        // },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // gray: colors.neutral,
        hotPink: '#FF1966',
        dark: '#111111',
        light: '#FAFAFA',
        violetDark: '#4c2889',
        'primary-clr': '#18191a',
        'secondary-clr': '#242526',
        'secondary-darker-clr': '#202122',
        'third-clr': '#3a3b3c',
        'fourth-clr': '#4e4f50',
        'fifth-clr': '#525355',
        'secondary-text': '#B0B3B8',
        'primary-text': '#E4E6EB',
        'primary-icon': '#E4E6EB',
        'hover-overlay': 'rgba(255, 255, 255, 0.1)',
        'red-notif': '#e41e3f',
        'primary-btn-icon': '#e4e6eb',
        'secondary-btn-bg': 'rgba(255,255,255,.1)',
        'primary-icon-clr-hover': '#4e4f50',
        'primary-icon-clr-active': '#3c3d3f',
        'comment-bg-clr-hover': '#292a2c',
        'blue-link': '#4599FF',
        'primary-deemphasized-bt-bg': 'rgba(45, 136, 255, 0.2)',
        'primary-deemphasized-bt-text': '#2D88FF',
        'primary-deemphasized-bt-hover': '#3c4d63',
        'disabled-icon': 'rgba(255, 255, 255, 0.3)',
        'blue-btb-bg-acitve': '#263950',
        'media-inner-border': 'rgba(255, 255, 255, 0.05)',
        'media-outer-border': '#33363A',
        divider: '#3E4042',
        accent: 'hsl(214, 100%, 59%)',
        'popover-bg': '#3E4042',
        'comment-bg': '#3a3b3c',
        'messenger-card-bg': '#242526',
        'comment-foot': '#4f4f50',
        wash: '#3E4042',
        'sec-btn-bg': '#4B4C4F',
        'sec-btn-bg-hover': '#5d5e61',
        'primary-btn-bg': '#2374e1',
        'primary-btn-bg-hover': '#3982e4',
        'surface-bg': '#242526',
        // hsl(214, 100%, 59%)
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@headlessui/tailwindcss')({ prefix: 'ui' }),
    require('tailwind-scrollbar')({ nocompatible: true }),
  ],
} satisfies Config;

export default config;
