import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { auth } from '@/auth'
import { Toaster } from '@/components/ui/sonner'
import { SessionProvider } from 'next-auth/react'
import Provider from '@/components/providers'
import NavBar from './_components/navBar'
import WindowChat from './_components/windowChat/WindowChat'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <Toaster/>
            <NavBar />
            <WindowChat />
            {children}
          </Provider>
        </body>
      </html>
    </SessionProvider>
  )
}
